---
- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nfs-kernel-server

- name: Ensure export dirs exists
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: Configure exports
  become: yes
  template:
    src: exports.j2
    dest: /etc/exports
  notify: reload nfs-server

- name: Enable and start service
  become: yes
  service:
    name: nfs-server
    state: started
    enabled: yes
